version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8888:8888"
    environment:
      - PROFILE=release
    volumes:
      - app_data:/server
volumes:
  app_data:
    driver: local
