server:
  port: 8888
  http2.enabled: true

spring:
  application.name: project-mnt
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://34.125.125.134:3306/project_mnt?characterEncoding=UTF-8&useUnicode=true&cachePrepStmts=true&useServerPrepStmts=true&reWriteBatchedInserts=true
      username: root
      password: 123123a@
      connection-timeout: 300_000
      maximum-pool-size: 10

jira:
  username: "dat.nt0401@gmail.com"
  access-token: "ATATT3xFfGF0cHHlEgzn592GRFo8PeTI4lLAkrCMmoRV4hXH1zvgnmJthie-TWoNqalv2hyTRuEkVsWxQ1jJiMVyrcHU-Ok4DatuvR7RG31uB6lXDQgWweZSSNHdcM_XJDkmbGFWqR-lLRauOKQo7QvfY7t-U_FJ-szxiyd4jESue4EAQeSyOcs=35B24F9E"
  base-url: "https://project-mnt.atlassian.net"

web:
  config:
    cors-allow-all: false
    corsOrigin: http://localhost:3000
