server:
  port: 8888
  http2.enabled: true

spring:
  application.name: project-mnt
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/project_mnt?characterEncoding=UTF-8&useUnicode=true&cachePrepStmts=true&useServerPrepStmts=true&reWriteBatchedInserts=true
      username: root
      password:
      connection-timeout: 300_000
      maximum-pool-size: 10

jira:
  username: "dat.nt0401@gmail.com"
  access-token: "ATATT3xFfGF094fsB1cio9RG0HqyBAYRzlEPSRj768ML_3YbsY2AvCdq9QZujTrS9KnIKVuD207jznf1K9dH3Xgklm6dFZ1kVn0delWPVwn3_lTIov9iRqQnoM4CLqUUhmNZPjVONSfs3udZB3sggzLIbARDXwoibNmGsu19-ByeZReYulQwY04=04D906E1"
  base-url: "https://project-mnt.atlassian.net"

web:
  config:
    cors-allow-all: false
    corsOrigin: http://localhost:3000
