---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy
  namespace: app
spec:
  encryptedData:
    OAUTH2_PROXY_CLIENT_SECRET: test
    OAUTH2_PROXY_COOKIE_SECRET: test
  template:
    metadata:
      name: oauth2-proxy
      namespace: app
